[build]
  publish = "."

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

# Disable SPA redirect fallback for .js files
[[redirects]]
  from = "/*.js"
  to = "/:splat"
  status = 200
  force = true
