[build]
  publish = "."

# Force correct MIME type for JS modules
[[headers]]
  for = "*.js"
  [headers.values]
   Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/javascript; charset=UTF-8"

# Disable SPA redirect fallback for .js files
[[redirects]]
  from = "/*.js"
  to = "/:splat"
  status = 200
  force = true
